### ISSUE TITLE
Create dependency files with `conda env export` instead of `conda list`

### ISSUE THREAD

**Issue by julibeg** [aggreen/MTB-CNN#1]
Hi there!
I'm trying to get your model running on my machine, but it looks like the `environment_reqs.txt` files were created by running `conda list`. However, as far as I know, there is no way to use such a file directly to create a new environment. I had to transform it with `awk` so that the format would be the same as the one used by `conda list -e` (which can be used with `conda create --file`). It might make it easier for others to re-create your environments if you used `conda env export` or `conda list -e` to export the dependencies.

PS: For other people running into the same issue, you can use 
```bash
conda create -n my_env_name -c conda-forge -c bioconda --file \
    <(awk 'BEGIN{OFS="="} $1 !~ "^#" {print $1, $2, $3}' environment_reqs.txt)
```
to create the environment from one of the provided files.

**Comment by aggreen** [comment]
Hi, thanks for noticing this! The most recent commit contains files generated with `conda list -e` to address this issue. Please let us know if there are further concerns.
