### ISSUE TITLE
CRyPTIC annotations

### ISSUE THREAD

**Issue by agentdr1** [aggreen/MTB-CNN#4]
Hi, 

thanks for your great work and sharing all the data annotations and codes! 
I am trying to find all the annotations for the CRyPTIC dataset using the file MTB-CNN/input_data/cryptic_dataset.csv 
Here i just find annotations for 8 antibiotics (ISONIAZID,RIFAMPICIN,ETHAMBUTOL,AMIKACIN,KANAMYCIN,MOXIFLOXACIN,LEVOFLOXACIN,ETHIONAMIDE) and can't find e.g. Pyrazinamide, as used in your study. Do you know where I can find the missing annotations, or did i missed smth?

**Comment by aggreen** [comment]
Hello, 

You are correct, unfortunately the CRyPTIC dataset only provides phenotypes for 8 of the 13 drugs we used in our study. Let me know if you have other questions.
